name: CI-CD

on:
  push:
    tags:
      - 'v*'
    
jobs:
  build:
    name: 'Build'
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: '_Solutions/GameFramework.sln'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore $env:SOLUTION

    - name: Build
      run: dotnet build $env:SOLUTION --configuration $env:BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test $env:SOLUTION /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
  deploy:
    name: 'Deploy'
    needs: [build]
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: '_Solutions/GameFramework.sln'

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 'Get Version'
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore $env:SOLUTION

    - name: Build
      run: dotnet build $env:SOLUTION --configuration $env:BUILD_CONFIG -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }} --no-restore

    - name: Pack Modules
      shell: pwsh
      run: '& .\Tools\PushArtifact.ps1 -Version ${{ steps.get_version.outputs.version-without-v }} -WorkDir .\Tools\ -Configuration Release'

    - name: Publish
      run: |
        dotnet nuget push .\Tools\Packages\${{ steps.get_version.outputs.version }}\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
        dotnet nuget push .\Tools\Packages\${{ steps.get_version.outputs.version }}\*.nupkg --source 'https://nuget.pkg.github.com/joshika39/index.json' --api-key ${{secrets.GIT_API_KEY}}
