name: CI-CD

on:
  push:
    tags:
      - 'v*'
    
jobs:
  deploy:
    name: 'Build, Test & Deploy'
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'GameFramework.Release.slnf'
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install .NET MAUI
      shell: pwsh
      run: |
        dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
        
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Restore dependencies
      run: nuget restore $env:SOLUTION

    - name: Build
      run: dotnet build $env:SOLUTION --configuration $env:BUILD_CONFIG

    - name: Run tests
      run: dotnet test $env:SOLUTION /p:Configuration=$env:BUILD_CONFIG --no-build --verbosity normal

    - name: Pack Modules
      shell: pwsh
      run: '& .\dotnet-tools\PackPackages.ps1 -EnvFile .\.env -CustomProjectsFile .projects.conf' 

    - name: Push to NuGet Modules
      shell: pwsh
      run: '& .\dotnet-tools\PushPackages.ps1 -CustomProjectsFile .projects.conf -Source https://api.nuget.org/v3/index.json -ApiKey  ${{secrets.NUGET_API_KEY}}'

    - name: Push to GitHub Modules
      shell: pwsh
      run: '& .\dotnet-tools\PushPackages.ps1 -CustomProjectsFile .projects.conf -Source https://nuget.pkg.github.com/joshika39/index.json -ApiKey  ${{secrets.GIT_API_KEY}}'
